### ISSUE TITLE
[Feature request] Support implicit component imports with vite-plugin-components

### ISSUE THREAD

**Issue by mehcode** [znck/vue-developer-experience#113]
**Is your feature request related to a problem? Please describe.**

When using the [`vite-plugin-components`](https://github.com/antfu/vite-plugin-components) plugin in Vue 3.0.4, the context is not set correctly when checking types in the template.

```
=> ./src/App.vue:3:4
Error :: Cannot find name 'SiteFooter'. (code 2304)
```

```vue
<template>
  <router-view class="flex-1" />
  <SiteFooter />
</template>
```

**Describe the solution you'd like**

I'm not sure. This may be considered out-of-scope of the project as vite is injecting the imports. 

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by znck** [comment]
You can use vueconfig.json to define global components. (need to document😌)

**Comment by mehcode** [comment]
Playing around with it and it doesn't seem to change the output of the `typecheck` command:

```
{
  "globalComponents": [
    "**/components/*.vue"
  ],
  "preferences": {
    "componentsDirectories": ["src/components"],
    "script": {
      "mode": "setup"
    }
  }
}
```

**Comment by mehcode** [comment]
Ah. The `insiders` release works with `globalComponents`. 👍 

---

Awesome work on this by the way 🎩
