### ISSUE TITLE
Typecheck ignore the errors in .vue files

### ISSUE THREAD

**Issue by cawa-93** [znck/vue-developer-experience#140]
**Describe the bug**
I created a simple component and added an obvious type error to it:
```vue
  setup() {
    const a: string = 1;
  },
```
PhpStorm highlights the error at this location. However, running type checking does not detect a problem in the `.vue` file.

```
$ npx --no-install @vuedx/vuedx-typecheck ./src/renderer
Running for C:\Users\kozac\Dev\vite-electron-builder\src\renderer

Found 0 errors.
```

**Info (please complete the following information):**
 - OS Windows
 - IDE PhpStorm 
 - TypeScript Version 4.1.3
 - @vuedx/typecheck: ^0.4.1

**Additional context**
 - Repo: https://github.com/cawa-93/vite-electron-builder/tree/bump-%40vuedx/typecheck
 - Problem file: https://github.com/cawa-93/vite-electron-builder/blob/bump-%40vuedx/typecheck/src/renderer/App.vue
 - tsconfig: https://github.com/cawa-93/vite-electron-builder/blob/bump-%40vuedx/typecheck/src/renderer/tsconfig.json

**Comment by znck** [comment]
The tsconfig file is not including .vue files. Either add them to files option or remove files option.

**Comment by cawa-93** [comment]
I expected this to work the same as when using `tsc --noEmit`:
I may not specify all files, only the entry point. And the compiler automatically scans the entire tree of dependent files. Example:

```ts
// bad.ts
export const s: string = 1;
```
```ts
// index.ts
import {s} from './bad';

console.log(s);
```
```
$ tsc --noEmit
bad.ts:1:14 - error TS2322: Type 'number' is not assignable to type 'string'.

1 export const s: string = 1;
               ~


Found 1 error.
```
```
$ npx @vuedx/vuedx-typecheck
Running for C:\Users\kozac\Dev\vite-electron-builder\src\renderer

Found 0 errors.
```
