### ISSUE TITLE
vuedx-typecheck check the dist directory

### ISSUE THREAD

**Issue by mohannad-musleh** [znck/vue-developer-experience#151]
**Describe the bug**
`vuedx-typecheck` command check the `dist` directory when the build command executed 

**To Reproduce**
1. Create a new vite project with vue-ts template
```bash
npm init @vitejs/app my-vue-app --template vue-ts
```
2. move to the project directory and install the dependencies
```bash
cd my-vue-app && npm install
```
3. run npm build script
```bash
npm run build

> my-vue-app@0.0.0 build /workspaces/my-vue-app
> vuedx-typecheck . && vite build

Running for /workspaces/my-vue-app

Found 0 errors.building for production...
[write] assets/logo.3b714202.png 6.69kb
[write] assets/index.6e614665.js 44.41kb, brotli: 16.02kb
[write] assets/index.c2910053.css 0.20kb, brotli: 0.12kb
[write] index.html 0.38kb
```
4. Run the build script again
```bash
npm run build

> my-vue-app@0.0.0 build /workspaces/my-vue-app
> vuedx-typecheck . && vite build

Running for /workspaces/my-vue-app

> dist/assets/index.6e614665.js:2:44995 - suggestion 6133: 'r' is declared but its value is never read.
```

note: when i remove the `dist` directory and run the build script again, it will work without any issues

**Expected behavior**
The vuedx-typecheck should exclude the dist directory

**Info (please complete the following information):**
 - OS: Linux
 - IDE: VS Code
 - Node Version: 14.15.2
 - NPM Version: 6.14.9
 - TypeScript Version: 4.1.3
 - Vue Version 3.0.5
 - vite version: 2.0.0-beta.12

**Additional context**
package.json
```json
{
  "name": "my-vue-app",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vuedx-typecheck . && vite build"
  },
  "dependencies": {
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.0.4",
    "@vue/compiler-sfc": "^3.0.5",
    "@vuedx/typecheck": "^0.4.1",
    "@vuedx/typescript-plugin-vue": "^0.4.1",
    "typescript": "^4.1.3",
    "vite": "^2.0.0-beta.12"
  }
}
```

**Comment by znck** [comment]
This should be fixed by #143. Confirm if it's fixed in insiders build.
