### ISSUE TITLE
It is not possible chain the typecheck result

### ISSUE THREAD

**Issue by cawa-93** [znck/vue-developer-experience#153]
```
 npx @vuedx/vuedx-typecheck --no-pretty --format rdjson | reviewdog.exe -name -f rdjson
```
Lead to error. As I understand it, this is because `vuedx-typecheck` always exit with code 2 if an error is found:
https://github.com/znck/vue-developer-experience/blob/3826967a498a7600ecd11cd7abcc5bedda0b2342/packages/typecheck/src/cli.ts#L227 even though the format is specified by json / rdjson

**Comment by znck** [comment]
I messed that up in refactoring 😬

It would be nice to have test for this.
