### ISSUE TITLE
Duplicated Hover Info With Vetur

### ISSUE THREAD

**Issue by XiNiHa** [znck/vue-developer-experience#171]
**Describe the bug**
When both VueDX and Vetur are installed, TS hover hints are displayed twice.

**To Reproduce**
1. Install both extensions
2. Hover on some TS content in Vue SFC
3. TS hover hints are displayed twice.

**Expected behavior**
Only one should be displayed. Not sure which extension should display it.

**Screenshots/Recording**
<img width="1468" alt="스크린샷 2021-01-19 오후 4 07 30" src="https://user-images.githubusercontent.com/8155259/104999673-98b88a80-5a70-11eb-816b-bd1cd36a3713.png">

**Info (please complete the following information):**
 - OS: macOS 11.1
 - IDE: VSCode
 - TypeScript Version: `4.1.3`
 - Vue Version: `3.0.5`
 - VueDX Version: `0.6.0`
 - Vetur Version: `0.31.3`

**Additional Context**
I'm currently working inside a monorepo. Not sure it matters or not.

**Comment by znck** [comment]
Both vetur and vuedx are providing hover info. There's ongoing work to include TS plugin in vetur, for the time being you have to disable one of the extension if you don't want duplicate hover info.

**Comment by davidbailey00** [comment]
Is there a way to disable Vetur's code checking while retaining syntax highlighting for single-file components? If I disable the entire Vetur extension, this also removes syntax highlighting features.

**Comment by znck** [comment]
You can use [this extension](https://marketplace.visualstudio.com/items?itemName=znck.vue) for syntax highlighting.
