### ISSUE TITLE
npm install @vuedx/typescript-plugin-vue failed

### ISSUE THREAD

**Issue by hardfist** [znck/vue-developer-experience#19]
It seems that the dependency `@vuedx/template-ast-types@0.1.0-alpha.13` is not published 
![image](https://user-images.githubusercontent.com/8898718/87630989-0a81e580-c769-11ea-9b7f-2d8c53e7d01c.png)

**Comment by cereschen** [comment]
can only use pnpm

**Comment by znck** [comment]
Use VS Code extensions, for now, https://marketplace.visualstudio.com/items?itemName=znck.vue-language-features-insiders.

Packages would be published soon, targeting Nov 30 for alpha release.
