### ISSUE TITLE
Instructions for providing types to *.vue imports breaks type checking

### ISSUE THREAD

**Issue by Robin-Hoodie** [znck/vue-developer-experience#202]
**Describe the bug**

Following the instructions in the `HelloWorld` component generated by `vue-ts` template breaks type checking with `vuedx-typecheck`

**To Reproduce**

- Run `yarn create @vitejs/app`
- Choose "vue-ts" as template
- `cd vite-project && yarn`
- Running `yarn vuedx-typecheck .` works at this point
- Follow instructions in generated `HelloWorld` component (Tick "Provide types for *.vue imports")
  - `yarn add -D @vuedx/typescript-plugin-vue`
  - `rm src shims/vue.d.ts`
  - Running `yarn vuedx-typecheck .` stops working at this point
  - Add to `tsconfig.json`: 
```
"plugins": [{
      "name": "@vuedx/typescript-plugin-vue"
}]
```
  - "Open VSCode command input" and "Search and run "Select TypeScript version" -> "Use workspace version""
( I assume this is not necessary for getting `vuedx-typecheck` to work again though)
-  Running `yarn vuedx-typecheck .` still does not work at this point

The following error is printed upon running `yarn vuedx-typecheck .`: 
> src/main.ts:3:18 - error 2307: Cannot find module './App.vue' or its corresponding type declarations.

**Expected behavior**

Following the instructions provided in the project template does not break type checking 

**Screenshots/Recording**

**Info (please complete the following information):**
 - OS [e.g. Windows/Mac/Linux] `Mac`
 - IDE `VS Code`
 - TypeScript Version `4.1.5`
 - Vue Version `3.0.5`

**Additional context**

Repo in which I ran the above instructions, running `yarn vuedx-typecheck .` errors: https://github.com/Robin-Hoodie/typecheck-vite-reproduce

**Comment by Robin-Hoodie** [comment]
My bad, I thought I was posting in the Vite repo 🤦

**Comment by bisubus** [comment]
@Robin-Hoodie Consider reopening it. This is vuedx problem, as confirmed in #vitejs/vite/issues/1993 . I've encountered the same problem with Vue CLI project, `import App from './App.vue'` is the correct way to import SFCs but it won't work with vuedx-typecheck.

**Comment by reactjser** [comment]
After I deleted `src/shims-vue.d.ts`, I encountered the problem: `Cannot find module './App.vue' or its corresponding type declarations.ts(2307)`, anyone knows how to fix it?
