### ISSUE TITLE
VSCode release

### ISSUE THREAD

**Issue by vegerot** [znck/vue-developer-experience#21]
Even though this plugin is still experimental, would it be a good idea to put this on the VSCode marketplace?  Obviously making sure to clearly advertise the current status of this project

**Comment by znck** [comment]
Auto published every Monday.

https://marketplace.visualstudio.com/items?itemName=znck.vue-insiders
https://marketplace.visualstudio.com/items?itemName=znck.vue-language-features-insiders

**Comment by vegerot** [comment]
Awesome!  Thank you 🙏
