### ISSUE TITLE
difference between --no-pretty and regular run

### ISSUE THREAD

**Issue by mithom** [znck/vue-developer-experience#217]
![image](https://user-images.githubusercontent.com/9282831/109868295-bda33e80-7c67-11eb-9176-4dac0bb577aa.png)

running with vs without --no-pretty results in no errors vs with error. As this should only impact the output, this is a big difference
the used file is a regular imported typescript file

**Comment by eratio08** [comment]
Related to https://github.com/znck/vue-developer-experience/issues/169

**Comment by mithom** [comment]
this issue does not add any extra information on top of the related issue, will close this one as to keep all information in the same place. my appologies for not finding to other issue first
