### ISSUE TITLE
Question: can @vuedx/typecheck be used as tsc with vue support?

### ISSUE THREAD

**Issue by xiaoxiangmoe** [znck/vue-developer-experience#22]
see https://github.com/vitejs/create-vite-app/pull/17/files#diff-226f2590d9b4e5717134aee8d0aa266f1e32c9d59c5928a32f1336d7204dc444R6-R13

We can use `tsc --noEmit` if there has no `.vue` file.

Can `@vuedx/typecheck` be used as `tsc --noEmit`?

**Comment by znck** [comment]
`tsc` does not load plugins; that's why `@vuedx/typecheck` exists. Yes, it is meant to be used in place of `tsc --noEmit` when projects have `.vue` files.

Related: https://github.com/microsoft/TypeScript/issues/16607
