### ISSUE TITLE
rename typecheck to vue-typecheck or vuedx-typecheck

### ISSUE THREAD

**Issue by xiaoxiangmoe** [znck/vue-developer-experience#23]
The name `typecheck` is too common. 

`"bin": "bin/typecheck.js",` in   package `@vuedx/typecheck` will add `node_modules/.bin/typecheck`. 

I think creating `node_modules/.bin/vue-typecheck` is better

**Comment by znck** [comment]
Will it work with `npx`?

**Comment by xiaoxiangmoe** [comment]
Renaming package name will work. For example, `@vuedx/vue-typecheck` or `@vuedx/vuedx-typecheck`

**Comment by xiaoxiangmoe** [comment]
Any update on this?

**Comment by znck** [comment]
I think we can rename using the "bin" field. `vuedx-typecheck` works for me.

Accepting PR 🙌

**Comment by xiaoxiangmoe** [comment]
@znck Can you told me how to rename bin field?

I have tried `"bin": { "vuedx-typecheck": "./bin/vuedx-typecheck.js" }` and `"bin": "./bin/vuedx-typecheck.js"` and it doesn't work.

**Comment by znck** [comment]
I'm not sure either. I'll try.

**Comment by xiaoxiangmoe** [comment]
It seems that the only way is change package name to `@vuedx/vuedx-typecheck`.

**Comment by znck** [comment]
Done: https://github.com/znck/vue-developer-experience/commit/f201c0d5c8a679e97ccec60b56cc773c9664fc48

**Comment by xiaoxiangmoe** [comment]
When will you publish it? I'll update it on https://github.com/vitejs/create-vite-app/blob/a9788e74cc72395469e234e6978a8a91e38b25fc/template-vue-ts/package.json#L6

**Comment by xiaoxiangmoe** [comment]
Oh, I see!
I can use `yarn add --dev @vuedx/typecheck@0.3.1-insiders-1606311019.0`

**Comment by znck** [comment]
You can use `@vuedx/typecheck@insiders` to get the latest build.
