### ISSUE TITLE
Renaming a vue file to .ts yields wrong file

### ISSUE THREAD

**Issue by pikax** [znck/vue-developer-experience#45]
when renaming `.vue` file to `.ts` typescript rename will rename the file to `${file}_________module`

**Comment by znck** [comment]
Are you renaming import statement or file from explorer?

**Comment by pikax** [comment]
File explorer in vscode

**Comment by znck** [comment]
This should be fixed by #35. Reopen if not fixed.

**Comment by pikax** [comment]
Still happens with the https://github.com/znck/vue-developer-experience/commit/252054da80afc0841b10fc91f321fe0e71acd660

**Comment by znck** [comment]
Is it possible for you to add a failing test case? 

> P.S. If you want to pair-and-debug, let me know on discord.
