### ISSUE TITLE
typecheck: no such file or directory 'HelloWorld.vue_________render.tsx'

### ISSUE THREAD

**Issue by cexbrayat** [znck/vue-developer-experience#58]
Using `@vuedx/typecheck` version `0.3.1-insiders-1604891675.0` I'm running into an error straight away in a bare CLI project.

Repro:
```
npx @vue/cli@ create vue-integration -m yarn --inlinePreset '{"useConfigFiles": true,"plugins": {"@vue/cli-plugin-typescript": {"classComponent": false},"vue-cli-plugin-vue-next": {}}}'
yarn add --dev --exact @vuedx/typecheck@insiders
yarn typecheck
```

Throws:
```
$ /vue-cli-tests/template-typechecking/node_modules/.bin/typecheck
Loading plugin from node_modules/@vuedx/typescript-plugin-vue/dist/index.cjs.js
Loading project from tsconfig.json
./src/components/HelloWorld.vue
===============================
Unexpected error. Please report 👉 https://github.com/znck/vue-developer-experience/issues/new
Error: ENOENT: no such file or directory, open '/vue-cli-tests/template-typechecking/src/components/HelloWorld.vue_________render.tsx'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at readFile (/vue-cli-tests/template-typechecking/node_modules/@vuedx/typecheck/bin/typecheck.js:23:31)
```

**Comment by cexbrayat** [comment]
I see you added `requires repro` to this issue.

In case you missed it there is a repro step, but I added a branch here to demonstrate the issue if you want: https://github.com/cexbrayat/template-typechecking/pull/3 

Just checkout the branch, run `yarn` and `yarn typechek`

**Comment by znck** [comment]
Thanks for the repro. 🙌

**Comment by cexbrayat** [comment]
Thank _you_ for the quick fix ;) Do you plan to release an insider version soon so we can give it a spin?

**Comment by znck** [comment]
Here: https://github.com/znck/vue-developer-experience/actions/runs/376007284

**Comment by cexbrayat** [comment]
Thanks! But it looks like the release job failed?

**Comment by znck** [comment]
😞 release token expired, updating.
