### ISSUE TITLE
Vue DX prefers renaming globally over destructuring rename

### ISSUE THREAD

**Issue by 3nuc** [znck/vue-developer-experience#65]
```ts
export default defineComponent({
  setup() {
    const {
      params: { id },
    } = useRoute();
   //renaming "{data, ...}" into "employeeData" with F2 turns it into "{employeeData, ...}" instead of "{data: employeeData, ..."
   //and also renames all usages of "data" in useRequest in the whole repo into employeeData
    const { data, isLoading: isEmployeeLoading, VkLoader } = useRequest(
      getSingleEmployee(id as string)
    );

    return {
      data,
      isEmployeeLoading,
      VkLoader,
    };
  },
});
```

Repro one liner to download repro case and open the example file:
```sh
git clone --single-branch --branch vuedx-destructuring-naively-renames-in-workspace https://github.com/3nuc/zio.git && code zio -- zio/src/modules/employee/pages/PageSingleEmployee.vue
```
1. Clone the repo and open this file https://github.com/3nuc/zio/blob/vuedx-destructuring-naively-renames-in-workspace/src/modules/employee/pages/PageSingleEmployee.vue 
2. On line 14 while your cursor is on the variable name `data`, press F2 and rename it to employeeData

**Expected behavior:**
`{data, isLoading: isEmployeeLoading, VkLoader} = useRequest(...)` turns into `{data: employeeData, isLoading: isEmployeeLoading, VkLoader} = useRequest(...)`

**Actual behavior:**
It's renamed to `{employeeData, ...}` which doesn't exist on useRequest.

It also globally changes the name of `data` to `employeeData` in 4-5 files. It's as if I was refactoring the 'data' name in useRequest itself, so Vue DX wants to rename `data` in all files that use useRequest. Like this: 
![image](https://user-images.githubusercontent.com/5359825/99433899-6e324000-290e-11eb-9593-67dde2aab801.png)

**Comment by znck** [comment]
Upstream issue.
