### ISSUE TITLE
@vuedx/typecheck: issue with latest insiders release

### ISSUE THREAD

**Issue by cexbrayat** [znck/vue-developer-experience#70]
Trying to install `"@vuedx/typecheck": "0.3.1-insiders-1605961078.0",` throws:

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../projectconfig
```

It looks like this commit ce906043e2b728d46acdfff8ae55a3b8091fe236 introduced the regression.

**Comment by znck** [comment]
It should have been workspace dependency. Fixing.
