### ISSUE TITLE
Questions about using vuedx-typecheck as tsc

### ISSUE THREAD

**Issue by xiaoxiangmoe** [znck/vue-developer-experience#79]
* vuedx-typecheck should exit with non-zero exit code if it has type errors
* vuedx-typecheck should print output same as tsc

**Comment by cawa-93** [comment]
> vuedx-typecheck should exit with non-zero exit code if it has type errors

There are cases when it is not worth exit with non-zero code, even if there was an error. 
For example, when you use a pipe to transfer the diagnostic result to another tool:
```bash
npx --no-install @vuedx/typecheck | reviewdog
```

**Comment by xiaoxiangmoe** [comment]
related: https://github.com/microsoft/TypeScript/issues/13280#issuecomment-383883065

**Comment by znck** [comment]
> - vuedx-typecheck should exit with non-zero exit code if it has type errors

It works like that in default mode. Though whenever an output mode (eg. json) is provided, it would always exit with zero.

> - vuedx-typecheck should print output same as tsc

This requires some work, feel free to raise a PR.

**Comment by cawa-93** [comment]
When I have time, maybe tomorrow, I can add a new `--fail-on-error` cli argument. If it is installed then the program will exit with non-zero code regardless of other arguments. @znck What do you think about it?

**Comment by xiaoxiangmoe** [comment]
In the future, maybe we should change options to be same as tsc. And the default behavior is fail on error.

**Comment by znck** [comment]
We support two kinds of output; parseable (json et.el.) and text. For text, we can exit with non-zero status. For parseable, always 0. WDYT?

**Comment by cawa-93** [comment]
> 
> 
> We support two kinds of output; parseable (json et.el.) and text. For text, we can exit with non-zero status. For parseable, always 0. WDYT?

This sounds quite logical. But it seems now with the `--json` flag, if there is an error, the exit will be with code 2. I can't check it at the moment, but I make this conclusion by looking at the code.

Only with the `--rdjson` flag the output will be code 0 regardless of the diagnostic result.

https://github.com/znck/vue-developer-experience/blob/c3d449a9c4ae0aee5c20b05f4ce75dffb6b7a321/packages/typecheck/bin/typecheck.js#L258-L282

I thought about introducing a separate flag to reconcile this behavior and make it independent from kinds of output.
