### ISSUE TITLE
vue-language-features: throwing errors on commented-out lines

### ISSUE THREAD

**Issue by andoshin11** [znck/vue-developer-experience#9]
Type checking within `<script/>` block works mostly fine, however I found somehow it keeps throwing errors even when I commend out the line which contains an error.

<img width="441" alt="Screen Shot 2020-04-19 at 22 54 03" src="https://user-images.githubusercontent.com/8381075/79689575-b615b980-8290-11ea-81ae-4ef09c4d0ee1.png">
<img width="582" alt="Screen Shot 2020-04-19 at 22 54 12" src="https://user-images.githubusercontent.com/8381075/79689578-b8781380-8290-11ea-9e22-c7e99dd6cb9e.png">

**Comment by znck** [comment]
This should be fixed but not released yet, I am planning to release an alpha by 30 November, so not accepting issues for the next few weeks.
