### ISSUE TITLE
Components imported in tests (Jest) throw overload errors on props

### ISSUE THREAD

**Issue by TheDutchCoder** [znck/vue-developer-experience#94]
If I have a component with, say, 2 props. Neither of them required, but have defaults and I mount a component with only 1 prop specified, the plugin will throw up on an overload.

Example:
```js
import Block from '@/components/Block'
import { mount } from '@vue/test-utils'

describe('Block', () => {
  it('should increase a', () => {
    const wrapper = mount(Block, {
      propsData: {
        heading: 'Foo',
      },
    })
    expect(wrapper.find('h1').text()).toBe('Foo')
  })
})
```

Component:
```html
<template>
  <h1>{{ heading }}</h1>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'

export default defineComponent({
  name: 'Block',

  props: {
    heading: {
      type: String,
      required: true,
    },

    subheading: {
      type: String,
      default: '',
      required: false,
    },
})
</script>
```

Error:
![image](https://user-images.githubusercontent.com/1668207/101951630-4d83a000-3bc5-11eb-8849-ecb5819c4b23.png)

**Comment by znck** [comment]
@pikax Do you have any suggestion here?

**Comment by pikax** [comment]
This is an issue with vue-test-utils types: https://github.com/vuejs/vue-test-utils-next/pull/274

**Comment by znck** [comment]
vuejs/vue-test-utils-next#274 is merged, closing this.
