### ISSUE TITLE
Support for multi dotted file name

### ISSUE THREAD

**Issue by pikax** [znck/vue-developer-experience#98]
Seems when you have multi dotted filename the types stop working

// component example
```vue
<template>
	<p>Value: {{value}}</p>
	<button @click="click">Increment</button>
</template>
<script>
import { defineComponent } from "vue";

export default defineComponent({
	props: {
		value: {
			type: Number,
			required: true
		},
	},

	methods: {
		click(){
			this.$emit('update:value', this.value+1)
		}
	}
})
</script>
```

If that file is saved with `Increment.Options.vue` it wont work, but if is saved as `IncrementOptions.vue` it will work.

```js
import _Ctx from './Increment.Options.vue?internal'


declare const __completionsTrigger: InstanceType<typeof _Ctx>
__completionsTrigger./*@@vue:completions*/$props
const __completionsTag = /*@@vue:completionsTag*/<div />
export function render({value, click,..._ctx}: InstanceType<typeof _Ctx>) {
  return /*@@vue:start*/<><p >Value: {value}</p><button onClick={click} >Increment</button></>/*@@vue:end*/
}
```

**Comment by znck** [comment]
Where do types support working? I need a repro to fix this.

**Comment by pikax** [comment]
You can check it here: https://github.com/pikax/vue-dx-porto/blob/break_dx/src/__tests__/components/options/Increment.spec.ts#L4 

works
![image](https://user-images.githubusercontent.com/4620458/102473949-f4e25600-404f-11eb-9387-a1a5b2df8e33.png)

doesn't work
![image](https://user-images.githubusercontent.com/4620458/102474000-04fa3580-4050-11eb-9a9a-0413d5434718.png)
